### PR TITLE
Windows Support!

### PR DESCRIPTION
**Pull request by Bassa31**
Hi AwslsomeAlex,
My name is bassa31 and I developved a version of your downloader for Windows
If you have a problem contact me ;) 
[windows.zip](https://github.com/AwlsomeAlex/ReactOS-Trunk-Downloader/files/214917/windows.zip)
I will create a exe with your modify

PS: This  script needs  CURL and 7-zip and Windows ;)

### CODE REVIEW

**Comment by AwlsomeAlex** [comment]
Bassa31, I appreciate your contribution to ReactOS Trunk Downloader and I appologies for the late repsonce, I will check it out and will tell you what I think. I did not expect this to be made tbh, so I thank you.

**Comment by AwlsomeAlex** [comment]
I have implemented that. Thank you for your time to make this. I will create a seperate branch with tools and scripts that you can use for future use. I again thank you.

**Comment by Bassa31** [comment]
Yeah!

**Comment by AwlsomeAlex** [comment]
I have made a separate branch called "windows" where you can checkout to and add your tools to making your testing environment easier. I again thank you for your contribution. @Bassa31

**Pull request closed without merging**
